# -*- coding: utf-8 -*-
"""changing_color.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/prestasicode/imageprocessing/blob/main/changing_color.ipynb
"""

import cv2 as cv

flags = [i for i in dir(cv) if i.startswith('COLOR_')]
print( flags )

import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
img = cv.imread('opencv_logo.png')
#assert img is not None, "file could not be read, check with os.path.exists()"

import numpy as np
from PIL import Image

def changeColor(image_file):

    im = Image.open(image_file)
    data = np.array(im)

    r1, g1, b1 = 55, 55, 55 # Original value
    r2, g2, b2 = 30, 57, 79 # Value that we want to replace it with

    red, green, blue = data[:,:,0], data[:,:,1], data[:,:,2]
    mask = (red == r1) & (green == g1) & (blue == b1)
    data[:,:,:3][mask] = [r2, g2, b2]
    
    image_file = image_file.replace(".png","")
    im = Image.fromarray(data)
    im.save(f'folder_name/{image_file}.png')
    
    return f"Done {image_file}"
